### ISSUE TITLE
Expand Readme

### ISSUE THREAD

**Issue by EoD** [rbray89/EnvironmentalVisualEnhancements#43]
It would be really great to expand the [Readme](https://github.com/rbray89/EnvironmentalVisualEnhancements/blob/master/README.md) in such a way that you make a short explanation of each dll you are using. So I can decide which dll to disable and which one not to.

It took me quite some time to figure out which dll makes the game unplayable (~5fps) and it would have saved me a lot of time to know which dll does what.

Something like
```
Atmosphere: Adds Clouds(?)
CelestialShadows: Adds Shadows...(?)
CityLights: Adds a texture overlay on Kerbin...(?)
EveManager: ?
PQSManager: ?!
ShaderLoader: Allows usage of shaders(?)
Terrain: ?!
Utils: ?
```

**Comment by rbray89** [comment]
You can't just remove the dll files. The idea is that you disable functionality by altering the configs, NOT screwing around with the core files. 

Out of curiosity, what are you talking about by "makes the game unplayable (~5fps) "

**Comment by EoD** [comment]
If you could expand the configs such that I can easily disable specific features of EVE, it would serve my purpose even more :)

EVE with its stock config and all dlls enabled, give me about 5fps on kerbin, up to 1fps when launching.

**Comment by rbray89** [comment]
The GUI is accessible via ALT+0. I'm working on a tool-tip system to provide small explanations of what the parameters do.

What version are you running that drops the frame rate so low? What machine/specs are you running? Do you have a log file for me to inspect?

**Comment by EoD** [comment]
I am running KSP 1.0.5 with EVE 1-05-4. I have a Phenom 1090T and a R9 380X with more than enough Ram.

What kind of log do you want?

**Comment by rbray89** [comment]
Standard KSP.log would suffice. I just want to check for exceptions.

There is no way that system is performing worse than my laptop with regular EVE installed...

**Comment by EoD** [comment]
Ok, I removed all other mods I have installed and used a stock KSP rocked: Around 10-15fps in the Space Centre, 10fps on the launchpad and 5-10fps during launch (down to 3fps when I am looking around while holding rightclick).

If I remove EVE, I get about 25-30fps in the Space Centre and almost everywhere else more.

GPU load is about 30-40%.
CPU load is 100% on one core (putting it to 3.9GHz Turbo), ~0% on the others.

Here is the log: https://gist.github.com/EoD/52bbb56666443bd51e5b

**Comment by rbray89** [comment]
That really is odd... I would have thought your CPU to be more powerful than that. I'd expect your stock install to get MUCH better performance than that. On my 4700HQ I can get >40 FPS easily during flight in stock and around 20-30 FPS with EVE. What resolution are you running in? I see you're running under Linux... I have yet to try running EVE/KSP in a linux install... What distro are you running? Kernel version? It's been a while since I've run a Linux build with an AMD configuration... Are the drivers still iffy? I know Nvidia is king when it comes to graphics drivers on Linux still. I"d strongly recommend a Windows install or swapping out graphics to a Nvidia card. I've started looking up performance numbers for AMD graphics implementations on Linux and it doesn't look good...

I have the dev builds available in my repo... Could you try running with https://github.com/rbray89/EnvironmentalVisualEnhancements/raw/master/x86-EVE.zip
You may want to delete the BoulderCo/windowedIVA.cfg file.

(As a side note, thanks for introducing me to github gist. It is a lot cleaner than pastebin!)

**Comment by rbray89** [comment]
Actually, it is starting to make sense... Your graphics drivers are probably the bottle neck here. There may be another solution, but I'm not sure what that would be. If you have windows on another partition, that would be what I would use with AMD graphics.

**Comment by EoD** [comment]
I also tested this on Windows (7) with the same performance impact.

**Comment by rbray89** [comment]
Ah, I forgot the original purpose of the issue :)

At this moment, the README is only for license information, so I won't be updating the README with that info.

**Comment by EoD** [comment]
Then it might be a good idea to rename the file to ``LICENSE.md`` or something similar, such that it is consistent with github's file naming scheme and it will not cause confusions like "Why is there an empty readme?" which I had.
